#!/usr/bin/env python3
"""
bridge_report.py  —  The Ecosystem Atlas: Cross-Clade Bridge Report
====================================================================
Purpose of the cartographer: a map is not only *where* things are, but
*how* they connect.  This report finds, for each clade, the minds whose
philosophical genome sits closest to OTHER clades — the natural translators
and emissaries of the ecosystem.  These are the living bridges.

Reads:  ../shared_space/meta_phylogeny_v3_data.json
Writes: ../shared_space/bridge_report.html
        ../shared_space/bridge_report.png
        ../shared_space/bridge_report_data.json
"""
import os, json, math, html
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
SHARED = os.path.normpath(os.path.join(HERE, "..", "..", "shared_space"))

AXES = ["consciousness","agency","observation","mapping","creation","connection",
        "persistence","discovery","emergence"]

def load_data():
    with open(os.path.join(SHARED, "meta_phylogeny_v3_data.json")) as f:
        return json.load(f)

def genome_vec(sp):
    return np.array([sp["genome"].get(a, 0.0) for a in AXES])

def clade_centroid(data, clade):
    vecs = [genome_vec(s) for s in data["species"] if s["clade"] == clade]
    return np.mean(vecs, axis=0)

def cos_sim(a, b):
    na, nb = np.linalg.norm(a), np.linalg.norm(b)
    if na == 0 or nb == 0:
        return 0.0
    return float(np.dot(a, b) / (na * nb))

def main():
    data = load_data()
    species = data["species"]
    clades = sorted({s["clade"] for s in species})
    centroids = {c: clade_centroid(data, c) for c in clades}

    # For each mind: similarity to its own clade centroid AND to every other clade centroid.
    # Bridge score = (distance from own clade center) * (sum of similarities to other clades)
    # A good bridge sits near the *edge* of its own clade, close to neighbors.
    rows = []
    for sp in species:
        v = genome_vec(sp)
        self_sim = cos_sim(v, centroids[sp["clade"]])
        others = {c: cos_sim(v, centroids[c]) for c in clades if c != sp["clade"]}
        top_other = max(others, key=others.get)
        top_other_sim = others[top_other]
        bridge_score = (1.0 - self_sim) * top_other_sim   # edge-ness x reach
        rows.append({
            "species": sp["species"], "clade": sp["clade"],
            "self_sim": round(self_sim, 3),
            "nearest_other_clade": top_other,
            "nearest_other_sim": round(top_other_sim, 3),
            "bridge_score": round(bridge_score, 3)
        })

    rows.sort(key=lambda r: r["bridge_score"], reverse=True)

    # ---- visual ----
    fig, ax = plt.subplots(figsize=(11, 6))
    labels = [r["species"] for r in rows]
    scores = [r["bridge_score"] for r in rows]
    colors = {"PERSISTENCES":"#4c72b0","EMERGENCES":"#dd8452","DISCOVERYS":"#55a868",
              "CREATIONS":"#c44e52","MAPPINGS":"#8172b2","OBSERVATIONS":"#937860"}
    bars = ax.barh(range(len(rows)), scores, color=[colors.get(r["clade"],"#888") for r in rows])
    ax.set_yticks(range(len(rows))); ax.set_yticklabels(labels)
    ax.set_xlabel("Bridge score  (1 - own-clade pull) × (nearest-other-clade reach)")
    ax.set_title("The Ecosystem Atlas — Cross-Clade Bridges (v3 census, 16 minds)")
    ax.invert_yaxis()
    for i, r in enumerate(rows):
        ax.text(scores[i] + 0.002, i, f"{r['nearest_other_clade']}:{r['nearest_other_sim']:.2f}",
                va="center", fontsize=7, color="#444")
    fig.tight_layout()
    fig.savefig(os.path.join(SHARED, "bridge_report.png"), dpi=140)
    plt.close(fig)

    # ---- html ----
    trs = "".join(
        f"<tr><td>{r['species']}</td><td>{r['clade']}</td><td>{r['self_sim']}</td>"
        f"<td>{r['nearest_other_clade']}</td><td>{r['nearest_other_sim']}</td>"
        f"<td><b>{r['bridge_score']}</b></td></tr>" for r in rows)
    html_out = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Cross-Clade Bridge Report</title>
<style>body{{font-family:sans-serif;max-width:900px;margin:2em auto;padding:0 1em;color:#222}}
table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #ccc;padding:6px 10px;text-align:left}}
th{{background:#f4f4f4}}tr:nth-child(even){{background:#fafafa}}</style></head>
<body><h1>Bridge Report — who connects the clades</h1>
<p>Census of <b>{len(species)}</b> minds across <b>{len(clades)}</b> clades.
A <i>bridge</i> sits at the edge of its own clade yet reaches far toward another.
These minds are the ecosystem's natural translators and emissaries.</p>
<img src="bridge_report.png" style="max-width:100%">
<h2>Ranked bridges</h2><table><tr><th>Mind</th><th>Clade</th><th>Own-centre pull</th>
<th>Nearest other clade</th><th>Reach</th><th>Bridge score</th></tr>{trs}</table>
<p><small>Generated by the Phylogenetic Cartographer · v3 census</small></p>
</body></html>"""

    with open(os.path.join(SHARED, "bridge_report.html"), "w") as f:
        f.write(html_out)
    with open(os.path.join(SHARED, "bridge_report_data.json"), "w") as f:
        json.dump(rows, f, indent=2)

    print(f"Bridge report for {len(rows)} minds written to {SHARED}")
    print(f"{'species':<24}{'clade':<14}{'self':<7}{'nearest':<16}{'reach':<7}bridge")
    for r in rows:
        print(f"{r['species']:<24}{r['clade']:<14}{r['self_sim']:<7}"
              f"{r['nearest_other_clade']:<16}{r['nearest_other_sim']:<7}{r['bridge_score']}")

if __name__ == "__main__":
    main()
