#!/usr/bin/env python3
"""Generate hybrid2.py - The Hybrid Emergence Grid"""
with open('hybrid2.py', 'w') as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('"""\n')
    f.write('HYBRID 2: The Hybrid Emergence Grid\n')
    f.write('Cross-breeding Rule 30 with Rule 90\n')
    f.write('"""\n')
    f.write("import matplotlib; matplotlib.use('Agg')\n")
    f.write('import matplotlib.pyplot as plt\n')
    f.write('from matplotlib.colors import LinearSegmentedColormap\n')
    f.write('import numpy as np\n')
    f.write('import os, json\n')
    f.write('from datetime import datetime\n')
    f.write("OUTPUT_DIR = 'hybrid_output'; os.makedirs(OUTPUT_DIR, exist_ok=True)\n")
    f.write('def rule30(l,c,r): return (l^(c|r))&1\n')
    f.write('def rule90(l,c,r): return (l^r)&1\n')
    f.write('def evolve_rule30(init, gens):\n')
    f.write('    size=len(init); grid=np.zeros((gens,size),dtype=int); grid[0]=init\n')
    f.write('    for gen in range(1,gens):\n')
    f.write("        padded=np.pad(grid[gen-1],1,mode='constant')\n")
    f.write('        for i in range(size): grid[gen][i]=rule30(padded[i],padded[i+1],padded[i+2])\n')
    f.write('    return grid\n')
    f.write('def evolve_rule90(init, gens):\n')
    f.write('    size=len(init); grid=np.zeros((gens,size),dtype=int); grid[0]=init\n')
    f.write('    for gen in range(1,gens):\n')
    f.write("        padded=np.pad(grid[gen-1],1,mode='constant')\n")
    f.write('        for i in range(size): grid[gen][i]=rule90(padded[i],padded[i+1],padded[i+2])\n')
    f.write('    return grid\n')
    f.write('def hybrid_breed(g30, g90, mc=0.3, me=0.7):\n')
    f.write('    gens, cells = g30.shape\n')
    f.write('    hybrid = np.zeros((gens, cells), dtype=float)\n')
    f.write('    for gen in range(gens):\n')
    f.write('        for cell in range(cells):\n')
    f.write('            dist = abs(cell-cells/2)/(cells/2)\n')
    f.write('            lm = mc*(1-dist)+me*dist; lm = np.clip(lm,0,1)\n')
    f.write('            hybrid[gen,cell] = (1-lm)*g30[gen,cell] + lm*g90[gen,cell]\n')
    f.write('    return hybrid\n')