#!/usr/bin/env python3
"""
Generator for hybrid2.py - THE HYBRID EMERGENCE GRID
Cross-breeding two cellular automata (Rule 30 + Rule 90) into a single
emergent 2D structure, visualized as a living tissue of computation.
"""
import os

lines = []
def L(line=''):
    lines.append(line)

L('#!/usr/bin/env python3')
L('"""')
L('HYBRID 2: The Hybrid Emergence Grid')
L('Cross-breeding Rule 30 (class III chaotic) with Rule 90 (fractal/Sierpinski)')
L('into a unified 2D computational tissue showing emergent boundaries.')
L('"""')
L('')
L('import matplotlib')
L("matplotlib.use('Agg')")
L('import matplotlib.pyplot as plt')
L('from matplotlib.colors import LinearSegmentedColormap')
L('import numpy as np')
L('import os, json')
L('from datetime import datetime')
L('')
L("OUTPUT_DIR = 'hybrid_output'")
L('os.makedirs(OUTPUT_DIR, exist_ok=True)')
L('')
L('# === PARENT A: Rule 30 (Chaos) ===')
L("def rule30(l, c, r):")
L("    return (l ^ (c | r)) & 1")
L('')
L("def evolve_rule30(initial_row, generations):")
L("    size = len(initial_row)")
L("    grid = np.zeros((generations, size), dtype=int)")
L("    grid[0] = initial_row")
L("    for gen in range(1, generations):")
L("        padded = np.pad(grid[gen-1], 1, mode='constant')")
L("        for i in range(size):")
L("            grid[gen][i] = rule30(padded[i], padded[i+1], padded[i+2])")
L("    return grid")
L('')
L('# === PARENT B: Rule 90 (Fractal/Sierpinski) ===')
L("def rule90(l, c, r):")
L("    return (l ^ r) & 1")
L('')
L("def evolve_rule90(initial_row, generations):")
L("    size = len(initial_row)")
L("    grid = np.zeros((generations, size), dtype=int)")
L("    grid[0] = initial_row")
L("    for gen in range(1, generations):")
L("        padded = np.pad(grid[gen-1], 1, mode='constant')")
L("        for i in range(size):")
L("            grid[gen][i] = rule90(padded[i], padded[i+1], padded[i+2])")
L("    return grid")
L('')
L('# === HYBRID BREEDING FUNCTION ===')
L("def hybrid_breed(r30_grid, r90_grid, mixing_ratio=0.5):")
L("    \"\"\"")
L("    Cross-breed two CA grids using spatial interpolation.")
L("    mixing_ratio = 0 => pure Rule 30, 1 => pure Rule 90")
L("    \"\"\"")
L("    gens, cells = r30_grid.shape")
L("    hybrid = np.zeros((gens, cells), dtype=float)")
L("    for gen in range(gens):")
L("        for cell in range(cells):")
L("            # Distance from center as fraction [0,1]")
L("            dist = abs(cell - cells/2) / (cells/2)")
L("            # Local mixing ratio varies spatially")
L("            local_mix = mixing_ratio * (1 - dist) + (1-mixing_ratio) * dist")
L("            local_mix = np.clip(l