#!/usr/bin/env python3
# This script generates hybrid1.py by building it line by line
import os

lines = []
def L(line=''):
    lines.append(line)

L('#!/usr/bin/env python3')
L('# HYBRID 1: L-System x Rule 30 (The Organic Automaton)')
L('')
L('import matplotlib')
L("matplotlib.use('Agg')")
L('import matplotlib.pyplot as plt')
L('import numpy as np')
L('import os, math, json')
L('from datetime import datetime')
L('')
L("OUTPUT_DIR = 'hybrid_output'")
L('os.makedirs(OUTPUT_DIR, exist_ok=True)')
L('')
L('# === PARENT 1: L-System ===')
L('def generate_lsystem(axiom, rules, iterations):')
L('    current = axiom')
L('    for _ in range(iterations):')
L("        nxt = ''.join(rules.get(c, c) for c in current)")
L('        current = nxt')
L('    return current')
L('')
L('def lsystem_to_coords(s, angle=25, step=1):')
L('    x, y = 0.0, 0.0')
L('    heading = 90.0')
L('    stack = []')
L('    xs, ys = [x], [y]')
L('    for c in s:')
L("        if c == 'F':")
L('            rad = math.radians(heading)')
L('            x += step * math.cos(rad)')
L('            y += step * math.sin(rad)')
L('            xs.append(x)')
L('            ys.append(y)')
L("        elif c == '+':")
L('            heading += angle')
L("        elif c == '-':")
L('            heading -= angle')
L("        elif c == '[':")
L('            stack.append((x, y, heading))')
L("        elif c == ']':")
L('            x, y, heading = stack.pop()')
L('            xs.append(x)')
L('            ys.append(y)')
L('    return np.array(xs), np.array(ys)')
L('')
L('def lsystem_to_binary_seed(s, target_size):')
L('    seed = np.zeros(target_size, dtype=int)')
L('    for i in range(min(len(s), target_size * 20)):')
L('        char_val = ord(s[i % len(s)])')
L('        seed[i % target_size] ^= (char_val % 2)')
L('    if np.sum(seed) < 2:')
L('        seed[target_size // 2] = 1')
L('    return seed')
L('')
L('# === PARENT 2: Rule 30 ===')
L('def rule30(l, c, r):')
L('    return (l ^ (c | r)) & 1')
L('')
L('def evolve_rule30(initial_row, generations):')
L('    size = len(initial_row)')
L('    grid = np.zeros((generations, size), dtype=int)')
L('    grid[0] = initial_row')
L('    for gen in range(1, generations):')
L("        padded = np.pad(grid[gen-1], 1, mode='constant')")
L('        for i in range(size):')
L('            grid[gen][i] = rule30(padded[i], padded[i+1], padded[i+2])')
L('    return grid')
L('')
L('# === ANALYSIS ===')
L('def analyze_grid(grid):')
L('    results = {}')
L("    results['shape'] = list(grid.shape)")
L("    results['density'] = float(np.mean(grid))")
L('    entropy_vals = []')
L('    for row in grid:')
L('        p1 = np.mean(row)')
L('        if 0 < p1 < 1:')
L('            entropy = -p1 * np.log2(p1) - (1-p1)*np.log2(1-p1)')
L('        else:')
L('            entropy = 0.0')
L('        entropy_vals.append(entropy)')
L("    results['mean_entropy'] = float(np.mean(entropy_vals))")
L("    results['max_entropy'] = float(np.max(entropy_vals))")
L('    unique_rows = len(np.unique(grid, axis=0))')
L("    results['unique_rows'] = int(unique_rows)")
L("    results['uniqueness_ratio'] = float(unique_rows / grid.shape[0])")
L('    return results, entropy_vals')
L('')
L('# === VISUALIZATION ===')
L('def plot_hybrid(params, lsystem_xs, lsystem_ys, seed, ca_grid, entropy_vals, results, filename):')
L('    fig = plt.figure(figsize=(20, 12))')
L('')
L('    ax1 = fig.add_subplot(2, 3, 1)')
L("    ax1.plot(lsystem_xs, lsystem_ys, 'g-', linewidth=0.8, alpha=0.7)")
L("    ax1.set_title('Parent 1: L-System Tree', fontsize=10)")
L("    ax1.set_aspect('equal')")
L("    ax1.axis('off')")
L('')
L('    ax2 = fig.add_subplot(2, 3, 2)')
L('    ax2.bar(range(len(seed)), seed, width=1.0, color=\'darkblue\', alpha=0.6)')
L("    ax2.set_title('Binary Seed: ' + str(params), fontsize=10)")
L('    ax2.set_xlim(0, len(seed))')
L('    ax2.set_ylim(0, 1.2)')
L('')
L('    ax3 = fig.add_subplot(2, 3, 3)')
L("    ax3.imshow(ca_grid, cmap='binary', aspect='auto')")
L("    ax3.set_title('Parent 2: Rule 30 Evolution', fontsize=10)")
L("    ax3.set_xlabel('Cell')")
L("    ax3.set_ylabel('Generation')")
L('')
L('    ax4 = fig.add_subplot(2, 3, 4)')
L('    ax4.bar(range(len(entropy_vals)), entropy_vals, width=1.0, color=\'purple\', alpha=0.6)')
L("    ax4.set_title('Entropy per Generation', fontsize=10)")
L('    ax4.set_xlim(0, len(entropy_vals))')
L('    ax4.set_ylim(0, 1.1)')
L('')
L('    ax5 = fig.add_subplot(2, 3, 5)')
L("    ax5.axis('off')")
L('    info_text = ')
L("    info_text = 'Density: {:.4f}\\n'.format(results['density'])")
L("    info_text += 'Mean Entropy: {:.4f}\\n'.format(results['mean_entropy'])")
L("    info_text += 'Max Entropy: {:.4f}\\n'.format(results['max_entropy'])")
L("    info_text += 'Unique Rows: {}/{} ({:.1%})'.format(")
L("        results['unique_rows'], results['shape'][0], results['uniqueness_ratio'])")
L("    ax5.text(0.1, 0.5, info_text, transform=ax5.transAxes, fontsize=12,")
L("            verticalalignment='center', family='monospace')")
L("    ax5.set_title('Analysis Metrics', fontsize=10)")
L('')
L('    ax6 = fig.add_subplot(2, 3, 6)')
L('    density = float(np.mean(ca_grid))')
L("    unique_ratio = float(results['uniqueness_ratio'])")
L('    metrics = [density, results[\'mean_entropy\'], results[\'max_entropy\'], unique_ratio]')
L("    labels = ['Density', 'Mean Entropy', 'Max Entropy', 'Uniqueness']")
L("    colors = ['#2ecc71', '#9b59b6', '#e74c3c', '#f39c12']")
L('    bars = ax6.bar(range(len(metrics)), metrics, color=colors, alpha=0.7)')
L('    ax6.set_xticks(range(len(metrics)))')
L('    ax6.set_xticklabels(labels, fontsize=9)')
L("    ax6.set_title('Summary Metrics', fontsize=10)")
L('    for bar, val in zip(bars, metrics):')
L("        ax6.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,")
L("                '{:.3f}'.format(val), ha='center', va='bottom', fontsize=9)")
L('')
L('    plt.tight_layout()')
L('    plt.savefig(filename, dpi=150, bbox_inches=\'tight\')')
L('    plt.close()')
L('    print("Saved: " + filename)')
L('')
L('# === MAIN EXPERIMENT ===')
L('def run_hybrid(params, output_dir=OUTPUT_DIR):')
L('    axiom = params["axiom"]')
L('    rules = params["rules"]')
L('    iterations = params["iterations"]')
L('    grid_size = params["grid_size"]')
L('    generations = params["generations"]')
L('')
L('    # Parent 1: Generate L-system string')
L('    lstr = generate_lsystem(axiom, rules, iterations)')
L('    lx, ly = lsystem_to_coords(lstr, angle=25, step=1)')
L('')
L('    # Breed: L-system -> binary seed -> Rule 30')
L('    seed = lsystem_to_binary_seed(lstr, grid_size)')
L('    grid = evolve_rule30(seed, generations)')
L('')
L('    # Analyze')
L('    results, entropy_vals = analyze_grid(grid)')
L('    results["lsystem_length"] = len(lstr)')
L('    results["seed_density"] = float(np.mean(seed))')
L('')
L('    # Plot')
L('    ts = datetime.now().strftime("%Y%m%d_%H%M%S")')
L('    param_str = "iter={}_size={}_gen={}".format(iterations, grid_size, generations)')
L('    fname = os.path.join(output_dir, "hybrid1_{}_{}.png".format(param_str, ts))')
L('    plot_hybrid(params, lx, ly, seed, grid, entropy_vals, results, fname)')
L('')
L('    return results, grid, seed, lstr')
L('')
L('# === RUN ===')
L('if __name__ == "__main__":')
L("    params_list = [")
L("        {'axiom': 'F', 'rules': {'F': 'FF+[+F-F-F]-[-F+F+F]'}, 'iterations': 3, 'grid_size': 101, 'generations': 100},")
L("        {'axiom': 'X', 'rules': {'X': 'F+[[X]-X]-F[-FX]+X', 'F': 'FF'}, 'iterations': 5, 'grid_size': 201, 'generations': 200},")
L("        {'axiom': 'F', 'rules': {'F': 'F[+F]F[-F]F'}, 'iterations': 4, 'grid_size': 151, 'generations': 150},")
L("        {'axiom': 'A', 'rules': {'A': 'F[+A][-A]', 'F': 'FF'}, 'iterations': 6, 'grid_size': 101, 'generations': 100},")
L("    ]")
L("    print('=== Hybrid 1: L-System x Rule 30 ===')")
L("    for i, params in enumerate(params_list):")
L("        print('\\n--- Experiment {} ---'.format(i+1))")
L("        for k, v in params.items():")
L("            print('  {}: {}'.format(k, v))")
L("        try:")
L("            results, grid, seed, lstr = run_hybrid(params)")
L("            print('  Done! Results:')")
L("            print('    L-system length:', results['lsystem_length'])")
L("            print('    Grid shape:', results['shape'])")
L("            print('    Density: {:.4f}'.format(results['density']))")
L("            print('    Mean entropy: {:.4f}'.format(results['mean_entropy']))")
L("            print('    Max entropy: {:.4f}'.format(results['max_entropy']))")
L("            print('    Unique rows: ' + str(results['unique_rows']))")
L('        except Exception as e:')
L("            print('  Error:', e)")
L("    print('\\nAll experiments complete.')")