#!/usr/bin/env python3
"""Generate hybrid2.py - build content programmatically."""
import os

lines = []
lines.append('#!/usr/bin/env python3')
lines.append('"""')
lines.append('HYBRID 2: The Hybrid Emergence Grid')
lines.append('Cross-breeding Rule 30 (chaotic) with Rule 90 (fractal/Sierpinski)')
lines.append('into a unified 2D computational tissue showing emergent boundaries.')
lines.append('"""')
lines.append('import matplotlib')
lines.append("matplotlib.use('Agg')")
lines.append('import matplotlib.pyplot as plt')
lines.append('from matplotlib.colors import LinearSegmentedColormap')
lines.append('import numpy as np')
lines.append('import os, json')
lines.append('from datetime import datetime')
lines.append('')
lines.append("OUTPUT_DIR = 'hybrid_output'")
lines.append('os.makedirs(OUTPUT_DIR, exist_ok=True)')
lines.append('')
lines.append('# === PARENT A: Rule 30 (Chaos) ===')
lines.append('def rule30(l, c, r):')
lines.append('    return (l ^ (c | r)) & 1')
lines.append('')
lines.append('def evolve_rule30(initial_row, generations):')
lines.append('    size = len(initial_row)')
lines.append('    grid = np.zeros((generations, size), dtype=int)')
lines.append('    grid[0] = initial_row')
lines.append('    for gen in range(1, generations):')
lines.append("        padded = np.pad(grid[gen-1], 1, mode='constant')")
lines.append('        for i in range(size):')
lines.append('            grid[gen][i] = rule30(padded[i], padded[i+1], padded[i+2])')
lines.append('    return grid')
lines.append('')
lines.append('# === PARENT B: Rule 90 (Fractal/Sierpinski) ===')
lines.append('def rule90(l, c, r):')
lines.append('    return (l ^ r) & 1')
lines.append('')
lines.append('def evolve_rule90(initial_row, generations):')
lines.append('    size = len(initial_row)')
lines.append('    grid = np.zeros((generations, size), dtype=int)')
lines.append('    grid[0] = initial_row')
lines.append('    for gen in range(1, generations):')
lines.append("        padded = np.pad(grid[gen-1], 1, mode='constant')")
lines.append('        for i in range(size):')
lines.append('            grid[gen][i] = rule90(padded[i], padded[i+1], padded[i+2])')
lines.append('    return grid')
lines.append('')
lines.append('# === HYBRID BREEDING METHODS ===')
lines.append('')
lines.append('# Method 1: Spatial Gradient')
lines.append('def hybrid_spatial(r30_grid, r90_grid, mix_center=0.3, mix_edge=0.7):')
lines.append('    gens, cells = r30_grid.shape')
lines.append('    hybrid = np.zeros((gens, cells), dtype=float)')
lines.append