{
    "import matplotlib.pyplot as plt": null,
    "from matplotlib.animation import FuncAnimation": null,
    "# Global variables": null,
    "fig, ax = plt.subplots(figsize=(8, 8))": null,
    "ax.set_axis_off()": null,
    "ani = None": null,
    "def switch_visualization(event):": null,
    "    global ani": null,
    "    if event.key == 'm':": null,
    "        # Switch to Mandelbrot set": null,
    "        ani.event_source.stop()": null,
    "        plt.close(fig)": null,
    "        execute_script('../../shared_space/compendium/fractalis_oneiricus_interactive.py')": null,
    "    elif event.key == 'j':": null,
    "        # Switch to Julia set": null,
    "        ani.event_source.stop()": null,
    "        plt.close(fig)": null,
    "        execute_script('../../shared_space/compendium/fractalis_oneiricus_julia_explorer.py')": null,
    "    elif event.key == 'b':": null,
    "        # Switch to Barnsley fern": null,
    "        ani.event_source.stop()": null,
    "        plt.close(fig)": null,
    "        execute_script('../../shared_space/compendium/fractalis_oneiricus_barnsley_fern.py')": null,
    "def execute_script(script_path):": null,
    "    global fig, ax, ani": null,
    "    # Clear the current figure and axis": null,
    "    plt.close(fig)": null,
    "    fig, ax = plt.subplots(figsize=(8, 8))": null,
    "    ax.set_axis_off()": null,
    "    # Execute the specified script": null,
    "    exec(open(script_path).read(), globals())": null,
    "    # Reconnect the key press event handler": null,
    "    fig.canvas.mpl_connect('key_press_event', switch_visualization)": null,
    "    # Start the animation": null,
    "    ani = fig.canvas.new_timer(interval=50)": null,
    "    ani.add_callback(lambda: plt.show(block=False))": null,
    "    ani.start()": null,
    "# Start the application": null,
    "print('Welcome to Fractalis Oneiricus!')": null,
    "print('Press m for Mandelbrot set, j for Julia set, or b for Barnsley fern.')": null,
    "execute_script('../../shared_space/compendium/fractalis_oneiricus_interactive.py')": null
}