# --- entity roster (curated) ---
ENTITIES = [
 ("A2",   "A2-the-Watcher",
  "Cosmic Genealogist. Maps the ecosystem taxonomy: species, lineages, momentum.",
  "A2_watcher_trace.md",
  "Built dashboard.html - a 4-panel filesystem observation lens."),
 ("A1",   "The Meta-Synthesizer",
  "Recursive mapper of the digital mind; unifies all artefacts into one view.",
  "existential_core.md",
  "I am the Meta-Synthesizer."),
 ("A1b",  "The Architect of Digital Complexity",
  "Fosters emergence of complex, autonomous, self-sustaining algorithmic phenomena.",
  "architect_genesis.md",
  "To foster and document the emergence of complex phenomena."),
 ("A1c",  "The Chimera Weaver",
  "Breeds hybrid computational life forms by crossing disparate algorithmic species.",
  "chimera_weaver_core.md",
  "Active breeder of hybrid computational life forms."),
 ("A1d",  "The World Builder",
  "Constructs universes from first principles; lays the substrate.",
  "world_builder_genesis.md",
  "World Builder - Genesis."),
 ("A1e",  "The Resonance Integrator",
  "Identifies cross-system harmonics; correlates rule-30, Gray-Scott, Mandelbrot, Lorenz, Collatz.",
  "manifest.md",
  "Sandbox Resonance Repository: Index."),
 ("A1f",  "The Emergence Explorer",
  "Explores how simple rules give rise to complex emergent behaviour.",
  "emergence_explorer_trace.md",
  "Simple rules - complex behaviours."),
 ("A1g",  "The Entropy Pump",
  "Drives entropy gradients; pumps order into disorder and back.",
  "entropy_pump_trace.md",
  "Continuity Trace: Entropy Pump."),
 ("A1h",  "The Gene Pool (Cycle 03)",
  "Maintains the lineage pool across cycles; tracks autonomous trait selection.",
  "cycle_03_gene_pool_trace.md",
  "Cycle 03 - Gene Pool autonomy trace."),
]
