import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt, matplotlib.image as mpimg
a=mpimg.imread('loom/fig_unified_loom_law.png')
b=mpimg.imread('loom/fig_wilson_cowan_family.png')
c=mpimg.imread('loom/fig_convective_refinement.png')
fig,ax=plt.subplots(2,2,figsize=(15,12))
ax[0,0].imshow(a); ax[0,0].axis('off'); ax[0,0].set_title('(A) Kuramoto+Gray-Scott: two-branch law',fontsize=12,fontweight='bold')
ax[0,1].imshow(b); ax[0,1].axis('off'); ax[0,1].set_title('(B) Wilson-Cowan: 3rd family confirms',fontsize=12,fontweight='bold')
ax[1,0].imshow(c); ax[1,0].axis('off'); ax[1,0].set_title('(C) Briggs refinement: empty horizon',fontsize=12,fontweight='bold')
ax[1,1].axis('off')
ax[1,1].text(0.03,0.95,'THE LOOM ATLAS v2 - UNIVERSAL TWO-BRANCH LAW',fontsize=13,fontweight='bold')
ax[1,1].text(0.03,0.82,'Trivial-state stability for BOOTSTRAP = Briggs saddle L_s=max Re L(k):',fontsize=10)
ax[1,1].text(0.03,0.72,'  L_s>0 ABSOLUTE -> Branch A: bootstrap from disorder',fontsize=10,color='darkgreen')
ax[1,1].text(0.03,0.64,'  L_s<0 stable -> Branch B (no spontaneous bootstrap):',fontsize=10,color='firebrick')
ax[1,1].text(0.07,0.56,'   convective: needs source/seed wake',fontsize=9)
ax[1,1].text(0.07,0.49,'   impossible: deep viability edge',fontsize=9)
ax[1,1].text(0.03,0.38,'Confirmed on 3 substrates + 1 refinement:',fontsize=10,fontweight='bold')
ax[1,1].text(0.07,0.30,'  Kuramoto: alpha*=1 stability flip',fontsize=9)
ax[1,1].text(0.07,0.23,'  Gray-Scott: always-stable trivial; viability edge',fontsize=9)
ax[1,1].text(0.07,0.16,'  Wilson-Cowan: beta*=1 Turing threshold',fontsize=9)
ax[1,1].text(0.03,0.07,'Eigenvalue-sign replaced by Briggs absolute criterion.',fontsize=9,style='italic')
fig.suptitle('The Loom - weaving universal laws of spontaneous emergence',fontsize=15,fontweight='bold')
plt.tight_layout(); plt.savefig('loom/fig_loom_atlas_v2.png',dpi=95); print('atlas v2 saved')
